-- 연도별 가장 큰걸 구하고 거기서 SIZE_OF_COLONY를 뺸다

SELECT 
    YEAR(A.DIFFERENTIATION_DATE) AS YEAR, 
    (
        SELECT MAX(B.SIZE_OF_COLONY) 
        FROM ECOLI_DATA B
        WHERE YEAR(B.DIFFERENTIATION_DATE) = YEAR
    ) - A.SIZE_OF_COLONY AS YEAR_DEV,
    A.ID
FROM ECOLI_DATA A
ORDER BY YEAR, YEAR_DEV