-- A.CREATED_DATE 가 2022년 10월꺼
-- B.CREATED_DATE 기준으로 ASC, A.TITLE ASC

SELECT A.TITLE, A.BOARD_ID, B.REPLY_ID, B.WRITER_ID, B.CONTENTS, DATE_FORMAT(B.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
FROM USED_GOODS_BOARD A
JOIN USED_GOODS_REPLY B
ON A.BOARD_ID = B.BOARD_ID
WHERE DATE_FORMAT(A.CREATED_DATE, '%Y') = '2022'
AND DATE_FORMAT(A.CREATED_DATE, '%m') = '10'
ORDER BY B.CREATED_DATE ASC, A.TITLE ASC